services:
  ingestor:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      KAFKA_CONSUMER_TOPIC: ingest-cards-tasks
      KAFKA_PRODUCER_STG_CARDS_TASKS: stg-cards-tasks
      KAFKA_PRODUCER_INGEST_SALES_TASKS: ingest-sales-tasks
      KAFKA_BOOTSTRAP_SERVERS: kafka-compose-kafka-broker-1:9092
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: ingests
    networks:
      - global

networks:
  global:
    external: true